### ISSUE TITLE
edtf: value incorrectly converted in date: property

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/py-mapzen-whosonfirst-export#18]
London: https://spelunker.whosonfirst.org/id/101750367/

This record has an `edtf:inception` date of "0043~", though that date is being converted to "2043" in the `date:` properties. I tested an export of the record with a value of  "0043?", instead, which didn't change anything.

Perhaps this is an issue with the `edtf` Python module, I'm not sure.

- http://www.loc.gov/standards/datetime/edtf.html
- https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/101/750/367/101750367.geojson
- https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/mapzen/whosonfirst/export/__init__.py#L172-L224

**Comment by thisisaaronland** [comment]
Yeah, it's a bug in the `edtf` library...

https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/mapzen/whosonfirst/export/__init__.py#L187-L197

**Comment by stepps00** [comment]
This is no longer an issue.. exportifying the record of London now results in:

```
    "date:inception_lower":"0043-01-01",
    "date:inception_upper":"0043-12-31",
```
