### ISSUE TITLE
Add opt_parser.add_option to wof-exportify to update all records in given directory

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/py-mapzen-whosonfirst-export#5]
Currently, the `wof-exportify` tool updates a single record based on the given ID. It would be helpful to add an additional `opt_parser.add_option` function to the `wof:exportify` tool that updates all .geojson records in a given directory or folder. This would be useful in cases where we create a new alt-geometry.geojson that needs Exportifying.

Currently, the command to Exportify the main .geojson file in the `/whosonfirst-data/data/858/373/17` directory would look like:

`wof-exportify -s /usr/local/mapzen/whosonfirst-data/data/ -i 85837317`

To update all .geojson files (main and alt-geometry files), a possible new command could look something like:

`wof-exportify -s /usr/local/mapzen/whosonfirst-data/data/ -a 85837317`

https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/scripts/wof-exportify#L37

**Comment by stepps00** [comment]
Should substitute [line 37](https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/scripts/wof-exportify#L37) with: 

`if options.alt:`
           ` feature = mapzen.whosonfirst.utils.load(source, id, alt=options.alt)`
     `   else:`
           ` feature = mapzen.whosonfirst.utils.load(source, id)`

And add the following to [line 20](https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/scripts/wof-exportify#L20):

`opt_parser.add_option('-a', '--alt', dest='alt', action='store', default=None, help='')`

**Comment by nvkelso** [comment]
Looks like this can be closed now?

**Comment by dphiffer** [comment]
Yeah, I think so! Please reopen if the alt geometry option gives you any trouble, @stepps00.

**Comment by stepps00** [comment]
Will do!
